"""Added permissions table

Revision ID: 2b77b9bd3c45
Revises: a5444be897bd
Create Date: 2025-02-16 20:04:20.829396

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b77b9bd3c45'
down_revision: Union[str, None] = 'a5444be897bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
