"""Added blocked_until to requests

Revision ID: 87efaaf35a55
Revises: 7f9f9bb76d91
Create Date: 2025-02-17 18:49:29.009712

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87efaaf35a55'
down_revision: Union[str, None] = '7f9f9bb76d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('blocked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'blocked_until')
    # ### end Alembic commands ###
