"""Update permissions table

Revision ID: 9b8c356c0283
Revises: c2da74d4e30a
Create Date: 2025-02-18 11:36:46.910702

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b8c356c0283'
down_revision: Union[str, None] = 'c2da74d4e30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('granted_at', sa.DateTime(), nullable=False))
    op.drop_column('permissions', 'can_manage_users')
    op.drop_column('permissions', 'can_manage_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('can_manage_requests', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('permissions', sa.Column('can_manage_users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('permissions', 'granted_at')
    # ### end Alembic commands ###
